module.exports = {
  // ...existing code...
  theme: {
    extend: {
      // ...existing code...
      animation: {
        'bounce-slow': 'bounce 2s infinite',
      },
      // ...existing code...
    },
  },
  // ...existing code...
};